name: outmap
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animate_do: ^3.3.3
  cloud_firestore: ^4.9.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.2
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  geolocator: ^10.0.1
  go_router: ^13.1.0
  google_fonts: ^6.0.0
  google_sign_in: ^6.1.5
  mapbox_gl: ^0.16.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
    - .env
